# Generated by Django 4.2.3 on 2023-07-07 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GejalaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_gejala', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PenyakitModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_penyakit', models.CharField(max_length=255)),
                ('detail_penyakit', models.TextField()),
                ('saran_penyakit', models.TextField()),
                ('gambar', models.ImageField(null=True, upload_to='penyakit/')),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('password1', models.CharField(max_length=200)),
                ('password2', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BasisPengetahuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bobot', models.FloatField()),
                ('gejala', models.ManyToManyField(to='cabai.gejalamodel')),
                ('penyakit', models.ManyToManyField(to='cabai.penyakitmodel')),
            ],
        ),
    ]
