# Generated by Django 4.2.3 on 2023-07-14 12:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cabai', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basispengetahuan',
            name='gejala',
        ),
        migrations.RemoveField(
            model_name='basispengetahuan',
            name='penyakit',
        ),
        migrations.AddField(
            model_name='basispengetahuan',
            name='gejala',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cabai.gejalamodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basispengetahuan',
            name='penyakit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cabai.penyakitmodel'),
            preserve_default=False,
        ),
    ]
